### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by juanjoayala01** [tassoruas/PxgBot#3]
Hey, could you tell me how did you get the PXG base pointer address? I tried many times on how to get a static address from pxf with cheat engine, but i never had luck. I would really appreciate if you help me learn this.

**Comment by tassoruas** [comment]
Yes @juanjoayala01, I can help you with that.
Contact me in Discord ``Zodyx#8168`` so we cantalk about it.

**Comment by juanjoayala01** [comment]
Just added you there. Thanks a lot.
