### ISSUE TITLE
Walking not working

### ISSUE THREAD

**Issue by betoxf** [tassoruas/PxgBot#4]
Seems like the program can´t see the coordinate of the caracter either my pokemon health it works with auto attack. i bould using 2022

**Comment by tassoruas** [comment]
Hey @betoxf!
The bot needs a rework, mainly in the cavebot functionalities.
It was created before the new interface, and since it reads a lot of information in the screen, almost everything is not working anymore.
I am trying to find some time to fix it and doing it little by little.
